import React, { useCallback, useEffect, useMemo, useState } from 'react'
import { CloudRain, RefreshCw, Wind, Droplets, Thermometer, AlertTriangle, Gauge } from 'lucide-react'
import { fetchDemoPrediction, fetchDemoRegions, DemoRegion, VarshaNetraPrediction } from '@services/varshanetraApi'

const rainLeads=[1,3,6,12,24,48,72]
const floodLeads=[1,3,6,12,24,48]
const fmt=(n:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:1}).format(n)

export default function Forecast(){
 const [regions,setRegions]=useState<DemoRegion[]>([]); const [region,setRegion]=useState('assam'); const [rainLead,setRainLead]=useState(3); const [floodLead,setFloodLead]=useState(6)
 const [p,setP]=useState<VarshaNetraPrediction|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 const run=useCallback(async()=>{setLoading(true);setError('');try{setP(await fetchDemoPrediction(region,rainLead,floodLead))}catch(e){setError(e instanceof Error?e.message:'Forecast unavailable.')}finally{setLoading(false)}},[region,rainLead,floodLead])
 useEffect(()=>{fetchDemoRegions().then(x=>setRegions(x.regions)).catch(()=>{})},[]); useEffect(()=>{run()},[run])
 const days=useMemo(()=>{if(!p)return []; const base=new Date(p.forecast_time); return Array.from({length:7},(_,i)=>{const d=new Date(base);d.setDate(d.getDate()+i); const factor=[1,1.15,.82,.62,.48,.38,.55][i]; return {date:d, rain:Math.max(0,p.rainfall_mm*factor), wind:((p.current_conditions?.wind_speed_ms??0)*3.6)*(1+[0,.25,-.12,-.2,.08,.15,-.05][i]), risk:i<2?'High Risk':i<4?'Moderate Risk':'Low Risk', label:i===0?'Today':i===1?'Tomorrow':d.toLocaleDateString('en-IN',{weekday:'short'})}})},[p])
 return <div className="p-6 h-full overflow-auto"><div className="max-w-6xl mx-auto">
  <div className="flex justify-between items-start gap-4 mb-5"><div><h1 className="text-4xl font-bold">7-Day Forecast</h1><p>Risk prediction and weather outlook for {regions.find(r=>r.id===region)?.label||region}</p></div><button onClick={run} disabled={loading} className="px-4 py-2 rounded-lg bg-status-info text-surface-base font-semibold flex gap-2 items-center"><RefreshCw className={loading?'w-4 h-4 animate-spin':'w-4 h-4'}/> Refresh</button></div>
  <div className="command-panel p-4 mb-5 grid grid-cols-1 md:grid-cols-3 gap-3"><select value={region} onChange={e=>setRegion(e.target.value)} className="bg-surface-secondary border border-surface-border rounded-lg p-3">{regions.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select><select value={rainLead} onChange={e=>setRainLead(+e.target.value)} className="bg-surface-secondary border border-surface-border rounded-lg p-3">{rainLeads.map(h=><option key={h} value={h}>Rainfall: {h}h</option>)}</select><select value={floodLead} onChange={e=>setFloodLead(+e.target.value)} className="bg-surface-secondary border border-surface-border rounded-lg p-3">{floodLeads.map(h=><option key={h} value={h}>Flood: {h}h</option>)}</select></div>
  {p&&<div className="command-panel p-4 mb-5 border-l-4 border-risk-high bg-risk-high/5"><div className="flex items-center gap-3"><AlertTriangle className="text-risk-high"/><div><b className="text-risk-high">{p.warning_level==='RED'||p.warning_level==='ORANGE'?'High Risk Alert':p.warning_level==='YELLOW'?'Moderate Risk Alert':'Monitoring Alert'}</b><p>Model rainfall: {fmt(p.rainfall_mm)} mm · Flood probability: {Math.round(p.flood_probability*100)}% · Thermo-Wind signal: {p.thermo_wind_signal.toFixed(2)}</p></div></div></div>}
  {error&&<div className="command-panel p-4 mb-5 text-risk-critical">{error}</div>}
  {loading&&!p?<div className="flex justify-center py-20"><RefreshCw className="animate-spin text-status-info"/></div>:p&&<>
   <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6"><Mini icon={CloudRain} title="Rainfall" value={`${fmt(p.rainfall_mm)} mm`} sub={p.rainfall_category}/><Mini icon={Droplets} title="Flood Probability" value={`${Math.round(p.flood_probability*100)}%`} sub={`${p.inundation_depth_m.toFixed(2)} m inundation`}/><Mini icon={Wind} title="Wind" value={`${fmt((p.current_conditions?.wind_speed_ms??0)*3.6)} km/h`} sub="Thermo-Wind input"/><Mini icon={Gauge} title="Confidence" value={`${Math.round(p.confidence*100)}%`} sub={`${p.warning_level} warning`}/></div>
   <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">{days.map((d,i)=><div key={i} className={`command-panel p-4 ${i===0?'ring-2 ring-status-info':''}`}><div className="flex justify-between"><div><b>{d.label}</b><div className="text-xs text-text-muted">{d.date.toISOString().slice(0,10)}</div></div><CloudRain className={`w-9 h-9 ${i<2?'text-status-info':'text-text-secondary'}`}/></div><p className="mt-4 font-semibold">{i<2?'Heavy rainfall expected':i<4?'Moderate rainfall':'Partly cloudy'}</p><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span>Temp</span><b>{28-i%3}°/{22-i%2}°C</b></div><div className="flex justify-between"><span>Rain</span><b>{fmt(d.rain)} mm</b></div><div className="flex justify-between"><span>Wind</span><b>{fmt(d.wind)} km/h</b></div></div><div className="mt-4 text-center rounded-md py-2 bg-surface-secondary border border-surface-border text-xs font-semibold">{d.risk}</div></div>)}</div>
   <div className="grid md:grid-cols-2 gap-5 mt-6"><section className="command-panel p-5"><h2 className="text-xl font-bold mb-4">Current atmospheric conditions</h2><div className="grid grid-cols-2 gap-3"><Info icon={Thermometer} label="Temperature" value={`${p.current_conditions?.temperature_c??'—'} °C`}/><Info icon={Droplets} label="Humidity" value={`${p.current_conditions?.relative_humidity_pct??'—'} %`}/><Info icon={Wind} label="Wind speed" value={`${fmt((p.current_conditions?.wind_speed_ms??0)*3.6)} km/h`}/><Info icon={Droplets} label="Soil moisture" value={`${p.current_conditions?.soil_moisture_pct??'—'} %`}/></div></section><section className="command-panel p-5"><h2 className="text-xl font-bold mb-4">Model explanation</h2><ul className="text-sm space-y-2">{p.top_contributing_features.slice(0,6).map((x,i)=><li key={i} className="flex gap-2"><span className="text-status-info">•</span>{x}</li>)}</ul><p className="text-xs text-text-muted mt-4">{p.data_source_notice}</p></section></div>
  </>}
 </div></div>
}
function Mini({icon:Icon,title,value,sub}:{icon:React.ElementType,title:string,value:string,sub:string}){return <div className="command-panel p-4"><Icon className="w-5 h-5 text-status-info mb-3"/><div className="text-xs text-text-muted">{title}</div><div className="text-2xl font-bold mt-1">{value}</div><div className="text-xs mt-1">{sub}</div></div>}
function Info({icon:Icon,label,value}:{icon:React.ElementType,label:string,value:string}){return <div className="bg-surface-secondary rounded-lg p-3"><Icon className="w-4 h-4 text-status-info mb-2"/><div className="text-xs text-text-muted">{label}</div><b>{value}</b></div>}
